### ISSUE TITLE
Feature Request: Scroll on volume indicator to change sound level

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#1]
Unmodified GNOME SHell has that feature.

**Comment by Ordissimo** [comment]
I'm putting this in place tomorrow

**Comment by SaucySauce** [comment]
Thanks m8.

**Comment by Ordissimo** [comment]
The scroll is available on the volume, I do not reproduce!

**Comment by SaucySauce** [comment]
Scroll on top of the indicator icon, not inside the widget.

**Comment by SaucySauce** [comment]
https://user-images.githubusercontent.com/38703177/112074607-35c59b80-8b66-11eb-988b-758cf0414a8b.mp4

This is stock behavior.

**Comment by Ordissimo** [comment]
I don't close the exit I have to wear the code for the 40.rc
Do you confirm the operation for the 3.38?

**Comment by SaucySauce** [comment]
Working perfectly fine on 3.38. Thanks. Closing the issue.
