### ISSUE TITLE
Thank You.

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#13]
Thank you for updating and improving this extension to work on .38 and 40. 

Adding the reboot option was a nice touch, I only noticed yesterday at 3am that it was missing. Can I just say that perhaps adding a section divider under Orientation Lock would be a good idea now that the session options are complete.

https://github.com/GustavoPeredo/Big-Avatar-Gnome-Shell-Extension this is just cosmetic but it looks good.

**Comment by Ordissimo** [comment]
I'm putting the separator in tomorrow! Now I'm going to sleep :)

**Comment by Ordissimo** [comment]
Fix with #14
