### ISSUE TITLE
Enhancement: Rely on system icons instead of extension provided.

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#16]
Most icons provided in the icons folder in the extension could be replaced by system/custom icon theme ones.

Maybe make the extension provided ones as a fallback if the custom icon theme doesn't provide the equivalent.

**Comment by Ordissimo** [comment]
Fixed by #6

**Comment by Ordissimo** [comment]
https://github.com/Ordissimo/Big-Sur-StatusArea/issues/6#issuecomment-812665735

**Comment by SaucySauce** [comment]
I think I'll close this issue. What has been done is done.
