### ISSUE TITLE
Add divider between Volume scrollbar and Volume Settings

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#2]
![Screenshot from 2021-03-21 17-58-43](https://user-images.githubusercontent.com/38703177/111917420-768eb900-8a6f-11eb-986d-00cbb8caed6c.png) ![Screenshot from 2021-03-21 17-58-38](https://user-images.githubusercontent.com/38703177/111917423-77274f80-8a6f-11eb-8963-9cb015829c94.png)
This behavior is present in other indicators of the extension as well as many indicators of other 3rd party extensions.
![Screenshot from 2021-03-21 18-07-28](https://user-images.githubusercontent.com/38703177/111917628-94105280-8a70-11eb-9bf7-1d14f6464854.png) ![Screenshot from 2021-03-21 18-10-16](https://user-images.githubusercontent.com/38703177/111917685-e94c6400-8a70-11eb-9653-d2f164d3e560.png)

**Comment by Ordissimo** [comment]
Hi @SaucySauce ,
Can you give me more details about your OS, the gnome-shell version.
I do not reproduce the problem.

![Capture d’écran du 2021-03-21 21-10-24](https://user-images.githubusercontent.com/10682892/111919402-1eb17b80-8a8a-11eb-9d75-eb62e39a2afc.png)

**Comment by SaucySauce** [comment]
I'm using latest 3.38 with AdwMod, it's a slight modification of the Adwaita theme.

**Comment by SaucySauce** [comment]
![Screenshot from 2021-03-21 19-29-08](https://user-images.githubusercontent.com/38703177/111919911-b9568e00-8a7b-11eb-8859-43b90c8af059.png)

I added code from the volume indicator and now it shows duplicate.         `this.menu.addMenuItem(new PopupMenu.PopupSeparatorMenuItem());`

**Comment by SaucySauce** [comment]
Weird. I removed what I added and now it's fine. Closing the issue.

**Comment by Ordissimo** [comment]
Weird. I removed what I added and now it's fine. Closing the issue.
![Capture d’écran du 2021-03-21 21-34-53](https://user-images.githubusercontent.com/10682892/111920089-73a2c100-8a8d-11eb-8be8-49bfea1def66.png)
