### ISSUE TITLE
Wifi/airplane icon from my icons theme is not good.

### ISSUE THREAD

**Issue by Tuxman2** [Ordissimo/Big-Sur-StatusArea#20]
Hi,

As you can see in the picture below, the airplane is in white but not the other icon.

![airplaneicon](https://user-images.githubusercontent.com/23556606/113304915-047d6600-92f2-11eb-9c49-ebf5dd4bd74e.png)

What is this first icon (in grey) and how can I have it in white ? 

Note: I'm using the WhiteSur icons theme, and gnome-shell dark theme (WhiteSur).

I also have an issue. When the wifi is activate on the panel, I don't have an icon for it. I only have a grey bar.

![wifinoicon](https://user-images.githubusercontent.com/23556606/113305898-04ca3100-92f3-11eb-8a3e-300e860f6970.png)

Thanks.

Regards.

**Comment by SaucySauce** [comment]
Unfortunately, we're bound by how complete the Adwaita icon theme is otherwise the extension would ask for files that don't exist in other installs.

I can't help a lot because I'm on desktop with no wifi or bluetooth.

Check your icon theme because the issue could be on their side, not entirely sure if Whitesur is full svg.

**Comment by SaucySauce** [comment]
I recommend a full svg icon theme, I use Newaita and it's among the most complete.

**Comment by SaucySauce** [comment]
If it's still the same it's probably an extension issue, if the icon blends with the color palette of other icons it's an issue with Whitesur.

**Comment by Tuxman2** [comment]
I was wrong, it's not the theme of WhiteSur Icons I use, but the theme of Mojave icons. And it's a full svg icon theme.

**Comment by SaucySauce** [comment]
Unfortunately I can't reproduce due to lack of hardware.

**Comment by Ordissimo** [comment]
Fixed by #6
