### ISSUE TITLE
[FEATURE REQUEST] Allow 'user' To Move To the Left or Replace Activities Button

### ISSUE THREAD

**Issue by dsreyes1014** [Ordissimo/Big-Sur-StatusArea#26]
Would it be possible to allow the 'User' section to be moved to the left.  The idea is to remove the activities button and replace it with 'User'.

**Comment by Ordissimo** [comment]
Hi @dsreyes1014, 
In the absolute everything is possible!
Leave me some time to look, which I can do.
Adding the move to the left seems coherent to me.

**Comment by Ordissimo** [comment]
I have not finished, tell me if this is what you expect?

**Comment by Ordissimo** [comment]
No feedback

**Comment by dsreyes1014** [comment]
So sorry i have not been using gnome lately due to my current workflow.  I've been checking this extension and didn't much changes.
