### ISSUE TITLE
Change Notifications Indicator Icon to Notifications Center Icon

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#3]
The current notifications indicator uses a magnifying glass although it makes more sense to use an icon that closely matches the Mac OS X notifications center. 
![Screenshot from 2021-03-21 18-16-57](https://user-images.githubusercontent.com/38703177/111917854-a474fd00-8a71-11eb-8b9f-331c80d91e11.png)

On gnome shell there's `open-menu-symbolic` or `view-list-bullet-symbolic` or `preferences-other-symbolic` which is similar. I mention these so it's less burden on you to have a specifically made icon and allow for 3rd party theming to supply a fitting icon so it doesn't look so mismatched.

**Comment by Ordissimo** [comment]
You are right, I don't like this icon, I like this one:  view-list-bullet-symbolic

**Comment by SaucySauce** [comment]
Yesterday I was making a merge request to make the indicators fetch a system wide icon in several places but couldn't get the code to apply it fully.

**Comment by Ordissimo** [comment]
I did not find an icon in the default theme.
I would probably work on 2 icons that I would propose to the theme in order to put them in the theme
