### ISSUE TITLE
[FEATURE REQUEST] Make night display indicator inside brightness indicator when disabled

### ISSUE THREAD

**Issue by Gasiyu** [Ordissimo/Big-Sur-StatusArea#33]
Hi, thank you so much for this amazing works.
I have some suggestions about this extensions. Is it possible to make the night display indicator inside the screen brightness indicator when it's disabled?.  Thank you.

**Comment by Ordissimo** [comment]
Hi @Gasiyu, 
I had never seen this indicator, so I tried to make it appear. The code was broken, it is corrected.
I think that your request loses its meaning.
If it suits you, I let you close the issue, update your branch
