### ISSUE TITLE
Bug: Lock screen causing volume increase

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#35]
Whenever the screen locks and I unlock it, the volume increases.

**Comment by Ordissimo** [comment]
Can you deactivate the extension and check if the bug is still present?
I don't reproduce?

**Comment by SaucySauce** [comment]
I'll check. It only started happening today. Not entirely sure if it was because I'm updating packages that are GNOME 40 specific whilst I'm still on 3.38, Arch.

**Comment by SaucySauce** [comment]
I'll close the issue. It seems like an issue between gnome 38 and 40 packages related to the shell on my Arch install as I'm forcing 3.38 shell for extension compatibility for the time being.
