### ISSUE TITLE
Bug: Divider line disappears in sound menu.

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#39]
It seems like performing changes or updates to user themes causes the disappearance of the divider line until the next login.

![Screenshot from 2021-04-17 10-43-34](https://user-images.githubusercontent.com/38703177/115110233-d0e54180-9f69-11eb-9567-2b600ea4d857.png) (Adwaita in the picture)

It only affects the extensions sound menu. My guess it has something to do with the microphone input volume slider code that shows up once in a while (my mic is always plugged in but the slider is rarely visible) and doesn't properly cope with the UI changes.

**Comment by Ordissimo** [comment]
hi @SaucySauce,
I have reproduced!

**Comment by SaucySauce** [comment]
Nice

**Comment by Ordissimo** [comment]
hi @SaucySauce 
Can you test with this commit [divider-sound-menu](https://github.com/Ordissimo/Big-Sur-StatusArea/tree/divider-sound-menu) ?
The problem seems to come from gnome-shell, I work around it by forcing the display of all sub objects of the sound menu.

**Comment by SaucySauce** [comment]
@Ordissimo So far so good.

**Comment by Ordissimo** [comment]
@SaucySauce ,I let you close if you confirm the good functioning :)
Thanks

**Comment by SaucySauce** [comment]
I'll keep it open for a little longer whilst I confirm that it's not affected by other factors.

**Comment by SaucySauce** [comment]
After further review I can say it's working well. I'll close the issue. If you decide to use a different method later on please reopen and ping me so I can do further testing. @Ordissimo
