### ISSUE TITLE
Change System Indicator to avatar-default-symbolic

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#4]
![Screenshot-20210321182634-752x643](https://user-images.githubusercontent.com/38703177/111918095-fec28d80-8a72-11eb-8ebb-6013c6d60a78.png)
Doesn't make much sense to use the power off icon.

**Comment by Ordissimo** [comment]
I don't understand?

![Capture d’écran du 2021-03-21 21-25-32](https://user-images.githubusercontent.com/10682892/111919798-11958c00-8a8c-11eb-8c45-81544460a33d.png)

**Comment by SaucySauce** [comment]
The avatar icon goes to the indicator icon instead of using the power off icon.

**Comment by SaucySauce** [comment]
![Screenshot from 2021-03-21 20-47-51](https://user-images.githubusercontent.com/38703177/111921996-1c99ed80-8a87-11eb-97c1-ec313700d24b.png)

where did I go wrong? I also updated the code of the changeIcon function to refer to _indicatorIcon.show or .hide
