### ISSUE TITLE
Only a question: Move some functions 

### ISSUE THREAD

**Issue by Ftamino** [Ordissimo/Big-Sur-StatusArea#40]
Am i able to move the  bluethooth and sound menu to the system menu ??

**Comment by Ordissimo** [comment]
The current design does not allow it. In the absolute everything is possible, it just has to be coherent.
If you have a pull-request, I invite you to submit it, for the rest it must be a setting that allows to change the natural behavior of this extension.

**Comment by Ordissimo** [comment]
No feedback
