### ISSUE TITLE
TODAY event information in calendar is missing

### ISSUE THREAD

**Issue by PePoDev** [Ordissimo/Big-Sur-StatusArea#42]
Extension
![image](https://user-images.githubusercontent.com/15852891/117325959-69147d80-aebb-11eb-9d0e-c80c64706239.png)

Default
![image](https://user-images.githubusercontent.com/15852891/117325859-539f5380-aebb-11eb-8a9c-22003041efaa.png)

**Comment by M4tT3d** [comment]
I also have this problem. I'm on arch linux 5.16 with gnome 41.3

**Comment by hyuri** [comment]
Happens to me too, except the events icon is there but invisible. When I turn the "Do Not Disturb" option, it shows up with the same icon used for the Notifications.

![image](https://user-images.githubusercontent.com/18584014/158388180-b05e57ec-7cec-450f-ba70-c8d10f3d7b0c.png)
