### ISSUE TITLE
Request: Bluetooth Icon Should Change When Disabled

### ISSUE THREAD

**Issue by jacob-emery** [Ordissimo/Big-Sur-StatusArea#43]
Hey, first of all thank you so much for this extension!
I have an issue with the Bluetooth: the Bluetooth icon does not change when enabling/disabling Bluetooth.
It would feel much more natural if the Bluetooth icon would look more "disabled" (e.g. dark if the top bar is black) when Bluetooth is disabled.
Thank you in advance!

**Comment by ioanmoldovan95** [comment]
Bumping this. I wanna add that it might be a bug actually, as I took a look at the code and the functionality seems to be implemented, but not working

**Comment by Ordissimo** [comment]
@AI-ien, Thanks for your contribution!
