### ISSUE TITLE
Request: Leave The Status Area Open When Turning On Bluetooth, WiFi, ...

### ISSUE THREAD

**Issue by jacob-emery** [Ordissimo/Big-Sur-StatusArea#45]
I think that offering the possibility to leave the status area open (in case of this extension it means that it is something that should hold for all indicators) when turning on wifi, bluetooth and night light would be really enjoyable.
I would love the menu to close only after I click again on the status area icon (in this case the indicator icon) or some other part of the desktop (for instance an open application, the desktop, some empty part in the top bar, ...).

I think it would be really useful because every time I want to connect to my Bluetooth headset I need to:

1. click on the Bluetooth icon
2. turn on Bluetooth
3. click on Bluetooth (again) 
4. click on the the text "Bluetooth On"
5. click on the name of my saved device if I am using the extension "Bluetooth quick connect" (enable, but it didn't work correctly)
6. click on Bluetooth (again) 
7. click on the the text "Bluetooth On" (again) 
8. click on the name of my saved device if I am using the extension "Bluetooth quick connect" (disable, because connection wasn't established properly)
9. click on Bluetooth (again) 
10. click on the the text "Bluetooth On" (again) 
11. click on the name of my saved device if I am using the extension "Bluetooth quick connect" (enable... again... and now works)

since the connection to my Bluetooth devices has to be initialized by me every single time.
It would be nice if the same task could be achieved with fewer steps:

1. click on Bluetooth
2. turn on Bluetooth
3. click on the name of my saved device if I am using the extension "Bluetooth quick connect" (directly, without opening the indicator menu again)
4. eventually quickly disable and enable again the connection to the device, in case it didn't connected correctly (directly, without opening the indicator menu another two more time)

Often I need to select a different WiFi network, so this clearly would be helpful also there.

Similarly as proposed in my other feature request, you could offer an option in the settings also for this feature (e.g. "Don't Immediately Close Status Area Indicators When Turning On Bluetooth/WiFi/Night Light").

**Comment by Ordissimo** [comment]
Hi @jacob-emery 
I understand your problem!
Your request requires redefining the basic "PanelMenu.Button" object of gnome-shell.
This would make this extension very difficult to maintain.
I invite you to make this request directly to gnome-shell: [gbome-shell](https://gitlab.gnome.org/GNOME/gnome-shell)

**Comment by jacob-emery** [comment]
Thank you for your reply.
I didn't think this was a "hard coded" component. I will make a request to gnome-shell, then :)
Thank you for letting me know the exact name of the affected object to report.

**Comment by Ordissimo** [comment]
The component concerned is `PanelMenu.Button`  which is provided by gnome-shell
