### ISSUE TITLE
Gnome 41 support ?

### ISSUE THREAD

**Issue by Tuxman2** [Ordissimo/Big-Sur-StatusArea#47]
Hi,

do you plan to update your extension for Gnome 41 ?

Thanks.

Regards.

**Comment by Ordissimo** [comment]
Hi @Tuxman2 ,

Fixed in https://github.com/Ordissimo/Big-Sur-StatusArea/tree/41
Publied in https://extensions.gnome.org/extension/4085/big-sur-status-area/

I was on scanner problems. Sorry for the delay.
