### ISSUE TITLE
Make gtk theme set indicator dimensions

### ISSUE THREAD

**Issue by SaucySauce** [Ordissimo/Big-Sur-StatusArea#5]
Instead of having to manually specify indicator padding every time to match the theme in use, allow for the indicators to follow the gtk theme standards.

![Screenshot from 2021-03-21 18-33-18](https://user-images.githubusercontent.com/38703177/111918335-2cf49d00-8a74-11eb-8bd0-6691b295763c.png)

Present here is the color picker indicator, kstatus indicator for 3rd party app indicators (Telegram shown here), clipboard indicator, pamac updates indicator, screenshot tool indicator, and your extension indicators. If I were to switch to a different theme, all indicators except yours would follow the theme's padding automatically.

**Comment by Ordissimo** [comment]
Indeed, it would be more fun!
You have opened a lot of issues, I will try to solve each problem if it is relevant.
But it's been a week since I discovered this project so please be understanding :)

**Comment by SaucySauce** [comment]
Thank you. You're doing amazing work. I tried forking panel-indicators to work on 3.38 a while ago but never could get it to work. You made it work really well.

**Comment by Ordissimo** [comment]
Can you look at this branch [desactivate-spacing](https://github.com/Ordissimo/Big-Sur-StatusArea/tree/desactivate-spacing) ? It allows to disable the space setting. Need to restart gnome shell for the right visual, I continue to work on it

**Comment by SaucySauce** [comment]
So far it works well. Only thing that doesn't work is that setting a custom padding and then disabling it it doesn't update to the theme padding.

Also, how do I stop the extensions app from forcing update?
![Screenshot-20210322225913-852x593](https://user-images.githubusercontent.com/38703177/112072856-4b38c680-8b62-11eb-8ad0-d2bdb507c19d.png)

**Comment by SaucySauce** [comment]
Update: it seems like other extensions, in this case it seems like it was "Remove Dropdown Arrows" that interfered with your extension, I've turned them on and off again and it's ok for now.

**Comment by SaucySauce** [comment]
Can you set it at a version higher than the one available on the gnome shell extensions website? Just an idea.

**Comment by SaucySauce** [comment]
Ok this is weird. I'm scanning all the extensions I have and the indicators have two size standards, one 2 pixels less than the other. Your extension uses the smaller or the standards.

![Screenshot from 2021-03-23 00-45-17](https://user-images.githubusercontent.com/38703177/112080212-16803b80-8b71-11eb-8dcc-ae33385f749e.png)

Top network indicator is manually adjusted to the bigger standard. Bottom is automatic.

**Comment by Ordissimo** [comment]
> So far it works well. Only thing that doesn't work is that setting a custom padding and then disabling it it doesn't update to the theme padding.

Yes, I need to see, to go through all the indicators and find the style applied to each.

**Comment by Ordissimo** [comment]
Can you comment this in the stylesheet.css file ?
```
/*.panel-status-menu-box>StIcon { 
    icons-size: 16px; padding: 4px;
}*/
```
Is this suitable?

**Comment by Ordissimo** [comment]
Le 2021-03-23 01:00, SaucySauce a écrit :
> So far it works well. Only thing that doesn't work is that setting a
> custom padding and then disabling it it doesn't update to the theme
> padding.
> 
> Also, how do I stop the extensions app from forcing update?

rename the folder and the uuid of metadata.json with the same name

**Comment by SaucySauce** [comment]
Ok, so it updates the padding when enabling/disabling the manual overwrite. BUT manually setting the padding doesn't work anymore and sets to 0px. On my end it's ok as automatic padding does the work just fine.

**Comment by SaucySauce** [comment]
> Can you comment this in the stylesheet.css file ?
> 
> ```
> /*.panel-status-menu-box>StIcon { 
>     icons-size: 16px; padding: 4px;
> }*/
> ```
> 
> Is this suitable?

Comment on what exactly?

**Comment by Ordissimo** [comment]
Comment on this:
```
.panel-status-menu-box>StIcon { 
    icons-size: 16px; padding: 4px;
}
```
in this file:
https://github.com/Ordissimo/Big-Sur-StatusArea/blob/master/stylesheet.css

**Comment by SaucySauce** [comment]
I changed padding: to 5px

**Comment by SaucySauce** [comment]
Now it's set to the bigger padding standard. the one 2px wider I mentioned from above.

**Comment by Ordissimo** [comment]
I am not good in English, can you give me more precision?
> Ok, so it updates the padding when enabling/disabling the manual overwrite. BUT manually setting the padding doesn't work anymore and sets to 0px. On my end it's ok as automatic padding does the work just fine.

**Comment by SaucySauce** [comment]
![Screenshot from 2021-03-23 16-13-17](https://user-images.githubusercontent.com/38703177/112188671-b6ca7480-8bf2-11eb-8125-67a12f23a646.png)
Ok so now everything is perfect.

**Comment by SaucySauce** [comment]
> I am not good in English, can you give me more precision?
> 
> > Ok, so it updates the padding when enabling/disabling the manual overwrite. BUT manually setting the padding doesn't work anymore and sets to 0px. On my end it's ok as automatic padding does the work just fine.

![Screenshot-20210323161435-1123x924](https://user-images.githubusercontent.com/38703177/112188852-e8434000-8bf2-11eb-8031-71d230c64de9.png)

This is what I mean.

**Comment by SaucySauce** [comment]
Disabling "Activate Indicator Spacing" allows for proper automatic spacing but now manual setting is broken.

**Comment by Ordissimo** [comment]
Inattention, thank you !

**Comment by Ordissimo** [comment]
If it is good for you I let you close

**Comment by SaucySauce** [comment]
Ok, give me a second to review it.

**Comment by SaucySauce** [comment]
It seems like manual setting of the padding still doesn't work. Thanks for the increase in padding to 5px.

**Comment by SaucySauce** [comment]
Wait. Still running older version.

**Comment by SaucySauce** [comment]
My bad.

**Comment by Ordissimo** [comment]
:-)

**Comment by SaucySauce** [comment]
![Screenshot from 2021-03-23 16-38-21](https://user-images.githubusercontent.com/38703177/112192110-3443b400-8bf6-11eb-8ad0-d7a7254e9fd7.png)

Your latest update. Nice. Thanks.

**Comment by SaucySauce** [comment]
Manual padding works perfectly fine.

**Comment by SaucySauce** [comment]
I think it's stable and good for Issue to be closed.
