### ISSUE TITLE
Power mode submenu missing when this extension is enabled.

### ISSUE THREAD

**Issue by rktesser** [Ordissimo/Big-Sur-StatusArea#51]
In Gnome 41 (Fedora 35), there's a neat submenu that allows to quickly change the power mode (Performance, Balanced, Power Saver).
When I enable this extension, however, this submenu completely disappears, forcing me to open the power settings window in order to switch power modes.

**Comment by Ordissimo** [comment]
Can you make me a capture ?

**Comment by Ordissimo** [comment]
No feedback
