### ISSUE TITLE
Big Sur Status Area not open settings

### ISSUE THREAD

**Issue by Darko393** [Ordissimo/Big-Sur-StatusArea#57]
The settings of extension bigSur-StatusArea@ordissimo.com had an error:
```
SyntaxError: missing ) after argument list
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:216:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by ronylee11** [comment]
i had this too!

**Comment by AI-ien** [comment]
Can confirm as well.

**Comment by Ordissimo** [comment]
Hi all,
Can you each give me the version of your gnome-shell?

**Comment by AI-ien** [comment]
$ gnome-shell --version
GNOME Shell 41.3

**Comment by Ordissimo** [comment]
Hi @AI-ien;
I pushed a new version yesterday, can you test? 
https://extensions.gnome.org/extension/4085/big-sur-status-area/

**Comment by AI-ien** [comment]
Yes, it is the same version 28 that causes error. I don't know if it is relevant, but Website button in extensions app points to 40.rc branch `https://github.com/Ordissimo/Big-Sur-StatusArea/tree/40.rc`

**Comment by Ordissimo** [comment]
Hi All,
Please excuse me, the migration to the new gnome-shell formalism has been complex.
I just tested on gnome-shell 41.3, it works!
The Fix https://github.com/Ordissimo/Big-Sur-StatusArea/commit/24ab752a287c03fdd5c3bd29c26ce9b13f7905bb
The corrected file : https://raw.githubusercontent.com/Ordissimo/Big-Sur-StatusArea/master/prefs.js
I pushed a fix version in the store (It is necessary to wait for the publication): https://extensions.gnome.org/extension/4085/big-sur-status-area/
Thanks for your feedback!

**Comment by Ordissimo** [comment]
The version 29 fixes this problem, it has just been released in https://extensions.gnome.org/extension/4085/big-sur-status-area/

**Comment by AI-ien** [comment]
All good! Thanks for your work.
