### ISSUE TITLE
Extension point conflict: there is already a status indicator for role NotificationIndicator

### ISSUE THREAD

**Issue by AI-ien** [Ordissimo/Big-Sur-StatusArea#58]
There is an error when toggle off extension. 

Extensions v28.
Gnome shell: 41.2
Clean install, all other extensions disabled.
Notification is set split from calendar.

![Screenshot from 2022-02-10 10-10-15](https://user-images.githubusercontent.com/33252703/153364778-21f30f2f-a510-4532-86f4-ddafa52861c0.png)

Edit.

This happens also after system lock or suspend.

**Comment by Ordissimo** [comment]
I'll work on it this weekend!
