### ISSUE TITLE
Random Crash 

### ISSUE THREAD

**Issue by kacastorp** [Ordissimo/Big-Sur-StatusArea#59]
After todays extention update the Big SurArea carshes after a while. The extension is marked with error. Some icons are gone while others remain. After log off and log in again it is working again until it crashes, which it does. 
I am on Fedora 35 with gnome-shell 41 on a TP x230

**Comment by luca-martino** [comment]
Same to me
- Fedora release 35
- GNOME Shell 41.3

**Comment by luca-martino** [comment]
After gnome lock/unlock:

gnome-shell[2368]: JS ERROR: Extension bigSur-StatusArea@ordissimo.com: Error: Extension point conflict: there is already a status indicator for role NotificationIndicator
                                           
                                                addToStatusArea@resource:///org/gnome/shell/ui/panel.js:956:19
                                                enable@/home/xeon/.local/share/gnome-shell/extensions/bigSur-StatusArea@ordissimo.com/extension.js:76:19
                                                _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:600:22
                                                _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:599:37
                                                _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:627:18
                                                _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                                _sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
                                                popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
                                                _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:532:30
                                                deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:523:44
                                                finish@resource:///org/gnome/shell/gdm/authPrompt.js:604:13
                                                finish@resource:///org/gnome/shell/ui/unlockDialog.js:885:26
                                                deactivate@resource:///org/gnome/shell/ui/screenShield.js:523:26
                                                ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:109:57
                                                _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                                _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19

**Comment by kacastorp** [comment]
Ther was an update but still the same. This is what I get: The settings of extension bigSur-StatusArea@ordissimo.com had an error:
```
SyntaxError: missing ) after argument list
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:216:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by luca-martino** [comment]
With latest release no more error/crash after gnome session lock/unlock 

> After gnome lock/unlock:
> 
> gnome-shell[2368]: JS ERROR: Extension [bigSur-StatusArea@ordissimo.com](mailto:bigSur-StatusArea@ordissimo.com): Error: Extension point conflict: there is already a status indicator for role NotificationIndicator
> 
> ```
>                                             addToStatusArea@resource:///org/gnome/shell/ui/panel.js:956:19
>                                             enable@/home/xeon/.local/share/gnome-shell/extensions/bigSur-StatusArea@ordissimo.com/extension.js:76:19
>                                             _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
>                                             _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:600:22
>                                             _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:599:37
>                                             _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:627:18
>                                             _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
>                                             _sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
>                                             popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
>                                             _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:532:30
>                                             deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:523:44
>                                             finish@resource:///org/gnome/shell/gdm/authPrompt.js:604:13
>                                             finish@resource:///org/gnome/shell/ui/unlockDialog.js:885:26
>                                             deactivate@resource:///org/gnome/shell/ui/screenShield.js:523:26
>                                             ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:109:57
>                                             _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
>                                             _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
> ```

**Comment by Ordissimo** [comment]
Hi @luca-martino and @kacastorp ,
I have made some corrections, can you update the extension and confirm the problem?

**Comment by kacastorp** [comment]
I will as soon as the update is available in extentions

**Comment by Ordissimo** [comment]
The version of the extension is 33, you can deactivate it and reactivate it!

**Comment by kacastorp** [comment]
In gnome-shell extentions it is listet as version 30. I did re-instal several times. But as said, it seems to be ok.
