### ISSUE TITLE
Time is Not Showing Correctly

### ISSUE THREAD

**Issue by ronylee11** [Ordissimo/Big-Sur-StatusArea#60]
supposedly be 11:32pm rn, but its showing 11:02pm, 30 minutes delayed
when extension is disabled it shows the correct time
extension: v29
gnome shell: 41.3
arch linux 5.16.8

![image](https://user-images.githubusercontent.com/64385071/153440807-007c3769-c30b-45f1-88ea-ae6bef841af9.png)

**Comment by ronylee11** [comment]
![image](https://user-images.githubusercontent.com/64385071/154072380-aa18e23e-ff18-456d-8e65-1dd3a410f89e.png)

**Comment by Ordissimo** [comment]
J'ai @ronylee11 
Can you execute these commands in a terminal and take a screenshot?
```
date
date +"%Z %z"
```

**Comment by ronylee11** [comment]
sure! there you go
![image](https://user-images.githubusercontent.com/64385071/154837153-6b499ec3-3c4a-472f-986e-f41327f92be9.png)

**Comment by Ordissimo** [comment]
@ronylee11 
Can you confirm that the correct date is the one on the console?

**Comment by ronylee11** [comment]
yes! the date on the console is indeed the correct one

![image](https://user-images.githubusercontent.com/64385071/154838879-a873c938-a04e-4254-9e60-5a500560a538.png)


it seems to me the date on the status bar is not updating live-ly, instead it happens from time to time, the time shown being delayed is not fixed 30 minutes delay, currently it shows 43 minutes delayed when im writing this

**Comment by Ordissimo** [comment]
Can you replace line 122 of the file $HOME/.local/share/gnome-shell/extensions/bigSur-StatusArea@ordissimo.com/indicators/calendar.js
`//this._date.setDate(now);`
with
`this._date.setDate(now);`

Send me a feedback

**Comment by ronylee11** [comment]
![image](https://user-images.githubusercontent.com/64385071/154860726-7a5c13f7-c398-4836-8164-9752adeedacf.png)
after changing it tried log out and log in, and even reboot, still doesnt work
i tried to rename the file calendar.js to calendar.js.bak, and the time is now accurate, it seems like the issue is indeed on the calendar.js file
![image](https://user-images.githubusercontent.com/64385071/154861355-54e25f58-d609-43a5-a2ef-1f82cb2d49ed.png)

**Comment by Ordissimo** [comment]
@ronylee11 
Can you confirm that the correct date is the one on the console?

**Comment by Ordissimo** [comment]
@ronylee11 
The message is gone with delay
> Can you confirm that the correct date is the one on the console?

I will continue to search, but I do not reproduce the problem!

**Comment by Alvfercas** [comment]
It seems like it always freezes at **:02.

It happened at 23:02 and now at 00:02.

**Comment by ronylee11** [comment]
is there any way to only disable the calendar modification?

**Comment by Ordissimo** [comment]
@ronylee11, why ?

**Comment by ronylee11** [comment]
sorry, my arch linux broke and i had to reinstall everything, the issue now no longer exists

**Comment by Ordissimo** [comment]
@ronylee11,
good news, thanks for the feedback
