### ISSUE TITLE
In Preferences "Position and Size" tab indicator toggles does not work

### ISSUE THREAD

**Issue by AI-ien** [Ordissimo/Big-Sur-StatusArea#66]
Well, this is weird bug and I don't know how to debug it. None of indicator toggles work, reposition toggles also does not work. So it's not possible to enable or disable indicators. Any other toggles work just fine, like indicator padding, battery percentage etc.

Edit. v27 works fine.

OS: Fedora 35
Gnome: 41.3
Version: 32 (from extensions page)

**Comment by Ordissimo** [comment]
I reproduce it!
Some callbacks didn't follow the migration, I'm looking for...
