### ISSUE TITLE
Battery Indiciator is showing xx.00%

### ISSUE THREAD

**Issue by jonasIam** [Ordissimo/Big-Sur-StatusArea#73]
Hello,
since a few days my laptop shows me the battery charge level with two 00´s. 
Since I do not need this information, I wanted to ask if anyone has an idea where this comes from or how to get rid of it.

Would be happy about an answer :)

![Bildschirmfoto vom 2022-03-05 17-59-00](https://user-images.githubusercontent.com/101013216/156892827-d5a61faa-c70d-4718-8dac-dc56832617c0.png)

**Comment by hyuri** [comment]
Same for me.

**Comment by Ordissimo** [comment]
Hi @jonasIam and @hyuri,
I take care of the gnome-shel l 42.0 compatibility and at the same time I will correct it!
In the file indicators/power.js line 80
replace this line:
```
this._percentageLabel.clutter_text.set_markup('<span size="smaller">' + this._power._proxy.Percentage.toFixed(2) + " %</span>");
```
with this one:
```
this._percentageLabel.clutter_text.set_markup('<span size="smaller">' + Math.round(this._power._proxy.Percentage) + " %</span>");
```

**Comment by jonasIam** [comment]
This worked wonderfully!
Thank you very much! 

Glad to hear the extension is coming to gnome 42 :)

**Comment by hyuri** [comment]
Worked perfectly. Thank you!
