### ISSUE TITLE
[Feature Request] Show indicator and menu for GSConnect

### ISSUE THREAD

**Issue by ItsWingyy** [Ordissimo/Big-Sur-StatusArea#78]
Hi,

Would you be able to allow the indicator for GSConnect (KDE Connect on Gnome) to be shown as currently it is hidden by this extension?

This is the extension: https://extensions.gnome.org/extension/1319/gsconnect/

Thanks

**Comment by Ordissimo** [comment]
Hi @ItsWingyy ,
I'm watching this weekend!

**Comment by Ordissimo** [comment]
Hi @ItsWingyy 
I've looked at it!
This extension is not integrated with gnome-shell, so I can't get these components safely.
The indicator is placed in the gnome-shell menu, ask to place it on the statusArea (I use this to do it: `Main.panel.addToStatusArea(indicator.name, indicator, 0, "right");`).
You should open an exit [GSConnect](https://github.com/GSConnect/gnome-shell-extension-gsconnect)

**Comment by Ordissimo** [comment]
It seems that it is planned to be able to move it, look at the picture :
![gsconnect](https://user-images.githubusercontent.com/10682892/160831383-b7c33437-b96a-40e6-b78d-3a77cec79f7b.png)
