### ISSUE TITLE
Outdated build dirrectory

### ISSUE THREAD

**Issue by n3rd3x3** [Ordissimo/Big-Sur-StatusArea#82]
When building using `ninja -C .build install`, this error is created:
```
ERROR: Build directory has been generated with Meson version 0.61.2, which is incompatible with the current version 0.62.0.
```

**Comment by Ordissimo** [comment]
Hi @n3rd3x3 
I need more information:
Distribution and Version

Did you delete the file and rebuild from source?

**Comment by Ordissimo** [comment]
Hi @n3rd3x3,
I just tested on ArchLinux with meson O.62
```
rm -rf .build 
meson .build
ninja -C .build install
```

**Comment by n3rd3x3** [comment]
Ok, thank you, I was able to solve this issue.
