### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by gregbug** [Ordissimo/Big-Sur-StatusArea#84]
i translated your extension to italian how i can send you the files ?
thx. for your work.
gianluca.

**Comment by Ordissimo** [comment]
use [pastebin](https://pastebin.com) and provide me with the link!

**Comment by gregbug** [comment]
here is the link:

<https://pastebin.com/3sJ81ntL>

thx.

Il giorno dom 17 apr 2022 alle 01:06:58 -0700, Ordissimo 
***@***.***> ha scritto:

**Comment by Ordissimo** [comment]
Hi @gregbug 
Thank you for your contribution!
