### ISSUE TITLE
wrong time in fedora 36 (gnome 42)

### ISSUE THREAD

**Issue by ayushhroyy** [Ordissimo/Big-Sur-StatusArea#88]
![image](https://user-images.githubusercontent.com/77523847/165954428-91e8be91-5aec-4aec-bfd9-0b0ddda2ccc5.png)

**Comment by mi-alkhamis** [comment]
hi, change the date format to %H:%M
it should work.

**Comment by ayushhroyy** [comment]
Thanks, it works now
Closing the bug
