### ISSUE TITLE
Option to keep some panel items stock

### ISSUE THREAD

**Issue by ImDedInside-git** [Ordissimo/Big-Sur-StatusArea#94]
Hey love your extension. Is there a way to use only the DATE and NOTIFICATION part and leave everything else stock since I want them to be separate?

**Comment by Ordissimo** [comment]
Yes, you can do this:
Open the extension's control panel, click on the "Position and size" tab
Disable "Unified Calendar/Notification Indicator".
Center Notification

Finish

**Comment by ImDedInside-git** [comment]
I think you misunderstood my question

I want this group and dropdown menu to still be there AND want only notification and date from the big sur extension (leave everything other than date and noti untouched)
![image](https://user-images.githubusercontent.com/67794677/169560105-f97145c7-c475-4b6a-be05-f012e82917ab.png)

**Comment by Ordissimo** [comment]
Ok, this is another extension what you are asking for...
