### ISSUE TITLE
System Settings does not load anything. 

### ISSUE THREAD

**Issue by johnmmcgee** [Ordissimo/Big-Sur-StatusArea#96]
Gnome 42 on Fedora 36

Clicking on my profile icon, all the way to the right, it appears when I click on system settings, nothing executes.

Let me know if more information is required.

**Comment by Ordissimo** [comment]
Hi @johnmmcgee , 
Can you provide me with the version of the extension?
Can you also give me the logs of journalctl concerning the extension?

**Comment by johnmmcgee** [comment]
Version: 45

This is what shows up when attempting to click the System Settings options, while executing the following command to log:

```
journalctl /usr/bin/gnome-shell -f -o cat
```

```
JS ERROR: TypeError: Shell.AppSystem.get_default().lookup_app(...) is null
_openApp@/home/phin/.local/share/gnome-shell/extensions/bigSur-StatusArea@ordissimo.com/indicators/button.js:44:39
_createSubMenu/<@/home/phin/.local/share/gnome-shell/extensions/bigSur-StatusArea@ordissimo.com/indicators/system.js:109:49
activate@resource:///org/gnome/shell/ui/popupMenu.js:197:14
vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:141:14
```

**Comment by Ordissimo** [comment]
Hi @johnmmcgee,
It seems that you don't have gnome-control-center, can you check?
`ls -l /usr/share/applications/gnome-control-center.desktop`

**Comment by johnmmcgee** [comment]
$ rpm -qa|grep gnome-control-center
gnome-control-center-42.3-1.fc36.x86_64

$ ls -l /usr/share/applications/gnome-control-center.desktop
lsd: /usr/share/applications/gnome-control-center.desktop: No such file or directory (os error 2).

Fedora 36

**Comment by Ordissimo** [comment]
Hi @johnmmcgee,
Could you tell me which desktop file runs "gnome-control-center"?
`grep -F 'gnome-control-center' /usr/share/applications/*
`

**Comment by johnmmcgee** [comment]
/usr/share/applications/org.gnome.Settings.desktop:Exec=gnome-control-center

**Comment by Ordissimo** [comment]
Hi @johnmmcgee 
I corrected, the version is being verified by gnome, then you can update!
Don't hesitate to tell me a problem ...

**Comment by Ordissimo** [comment]
You can update!

**Comment by johnmmcgee** [comment]
works! thank you.
